In [2]:
import numpy as np

In [7]:
l = [1,2,3,4]
np_arr = np.array(l)
print(np_arr, type(np_arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [9]:
#shape attribute returns number of element in each dimension
np_arr.shape

(4,)

In [ ]:
l = list(range(0,12))
np_arr = np.array(l)

np_arr.shape


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
np_arr_3d = np_arr.reshape((2,2,3))
print(np_arr_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
#ndim attribute provides the number of dimension of numpy array.
np_arr_3d.ndim

3

In [19]:
np_arr_2d = np_arr.reshape((3,4))
np_arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np_arr_2d[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np_arr_2d[2] #access dim1 element and that is arrayu of index 2

array([ 8,  9, 10, 11])

In [26]:
np_arr_2d[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [21]:
np_arr_2d[2][1]

np.int64(9)

In [24]:
np_arr_2d[2,1]

np.int64(9)